name: Custom Docker Build Action
description: Builds a Docker image with configurable Dockerfile path and naming
inputs:
  path_dockerfile:
    description: Path to the Dockerfile
    required: false
    default: "Dockerfile"
  image_name:
    description: Name for the generated Docker image
    required: true
  tag_name:
    description: Tag for the generated Docker image
    required: false
runs:
  using: composite
  steps:
    - run: |
        if [ -z "$TAG_NAME" ]; then
          export TAG=$(date +%s)
        else
          export TAG="$TAG_NAME"
        fi
        docker build \
          -f "${{ inputs.path_dockerfile }}" \
          -t "${{ inputs.image_name }}:${{ inputs.tag_name }}" \
          .
        echo "Built image: "${{ inputs.image_name }}:${{ inputs.tag_name }}"
      