name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  PATH_DOCKERFILE: ${{ inputs.path_dockerfile }}
  IMAGE_NAME: ${{ inputs.image_name }}
  TAG_NAME: ${{ inputs.tag_name }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn -B package --file pom.xml
    
    - name: Run Docker
      run: docker build . --file Dockerfile --tag academy:$(date +%s)
    
    - name: List Docker Images
      run: |
          echo "Listing all Docker images:"
          docker images

    - name: Maven Build
      uses: ./.github/actions/maven_build

    - name: Build Docker Image
      uses: ./.github/actions/docker_build
      with:
        path_dockerfile: Dockerfile
        image_name: academy
        tag_name: main