name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  PATH_DOCKERFILE: ${{ inputs.path_dockerfile }}
  IMAGE_NAME: ${{ inputs.image_name }}
  TAG_NAME: ${{ inputs.tag_name }}
  ARTIFACT_NAME: ${{ inputs.artifact_name }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Maven Build
      uses: ./.github/actions/maven_build

    - name: Build Docker Image
      uses: ./.github/actions/docker_build
      with:
        path_dockerfile: Dockerfile
        image_name: academy
        tag_name: main

    - name: Save docker Image
      run: |
        echo "Saving image ${{env.IMAGE_NAME}}:${{env.TAG_NAME}}"
        docker save "${{env.IMAGE_NAME}}:${{env.TAG_NAME}}" -o "${{env.ARTIFACT_NAME}}.tar"
      shell: bash
      env:
        IMAGE_NAME: academy
        TAG_NAME: main
        ARTIFACT_NAME: academy-image

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.ARTIFACT_NAME }}
        path: ${{ env.ARTIFACT_NAME }}.tar

  list-images:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Download Artifact
      uses: actions/download-artifact@v4
      with:
        name: ${{ env.ARTIFACT_NAME }}

    - name: Load Docker Image
      run: |
        docker load -i ${{ env.ARTIFACT_NAME }}.tar

    - name: List images
      run: docker image ls